/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import com.dataStructures.MyContainer;
import com.dataStructures.MyVisitor;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JLayer;
import javax.swing.JOptionPane;
/**
 *
 * @author Nuhu Ibrahim
 */
public class CustInfo extends javax.swing.JDialog {

    /**
     * Creates new form CustInfo
     */
    ProcessSales main;
    public CustInfo(java.awt.Frame parent, boolean modal, ProcessSales main) {
        super(parent, modal);
        this.main=main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uDemo16 = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        uDemo14 = new javax.swing.JLabel();
        custNumber = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        complete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 153), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("Cust. Name");
        jPanel1.add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        custName.setBackground(new java.awt.Color(204, 204, 255));
        custName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        custName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 380, -1));

        uDemo14.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo14.setForeground(new java.awt.Color(0, 0, 102));
        uDemo14.setText("Cust. Number");
        jPanel1.add(uDemo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        custNumber.setBackground(new java.awt.Color(204, 204, 255));
        custNumber.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        custNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(custNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 380, -1));

        close.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        close.setText("Close");
        close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 90, 35));

        complete.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        complete.setText("Complete Transaction");
        complete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeActionPerformed(evt);
            }
        });
        jPanel1.add(complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
        main.unblur();
    }//GEN-LAST:event_closeActionPerformed

    public String ucfirst(String s){
        try{
            String first, second;
            first=s.substring(0,1);
            second=s.substring(1);
            return first.toUpperCase()+second.toLowerCase();
        }catch(Exception ex){
            return "";
        }
    }
    
    private void completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeActionPerformed
        String custName=this.custName.getText().trim();
        String custNumber=this.custNumber.getText().trim();

        custName=custName.toUpperCase();

        MyContainer c= new MyContainer();

        String patName = "^[a-zA-Z0-9].{3,30}$";
        String PatMobile="\\+?[0-9]{1,20}$";

        if(!Pattern.matches(patName, custName)){
            c.insert("Invalid customer name");
        }
        if(!Pattern.matches(PatMobile, custNumber)){
            c.insert("Invalid customer phone number");
        }
        
        if(this.custName.getText().equals("") || this.custNumber.getText().equals("")){
            JOptionPane.showMessageDialog(CustInfo.this, "Empty Fields","Error!",JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else if(c.getCount()!=0){
            MyVisitor v= new MyVisitor();
            c.accept(v);

            JOptionPane.showMessageDialog(CustInfo.this,v.getErrors(), "Error!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                DBConnect.con.setAutoCommit(false);
                String sql="select * from tempSalesTbl";
                DBConnect.rs=DBConnect.st.executeQuery(sql);
                while(DBConnect.rs.next()){
                    String type = DBConnect.rs.getString("type");
                    java.util.Date today= new java.util.Date();
                    SimpleDateFormat ft= new SimpleDateFormat("yyyy-MM-dd");
                    String date= ft.format(today);

                    PreparedStatement st;
                    sql="insert into salestbl values (?,?,?,?,?,?,?,?)";
                    st=DBConnect.con.prepareStatement(sql);
                    st.setString(1, DBConnect.rs.getString("ID"));
                    st.setString(2, DBConnect.rs.getString("name"));
                    st.setString(3, DBConnect.rs.getString("quantity"));
                    st.setString(4, DBConnect.rs.getString("amount"));
                    st.setString(5, DBConnect.rs.getString("date"));
                    st.setString(6, DBConnect.rs.getString("type"));
                    st.setString(7, custName);
                    st.setString(8, custNumber);
                    st.executeUpdate();

                    DBConnect db= new DBConnect();
                    sql="select * from inventory where productID=?";
                    st=db.con.prepareStatement(sql);
                    st.setString(1, DBConnect.rs.getString("ID"));
                    ResultSet rst=st.executeQuery();
                    int oldQty=0;
                    if(rst.next()){
                        oldQty=rst.getInt("Qty");
                    }

                    if(type.equals("PRODUCT")){
                        sql="insert into inventorytrack values (?,?,?,?,?,?,?)";
                        st= DBConnect.con.prepareStatement(sql);
                        st.setString(1, DBConnect.rs.getString("ID"));
                        st.setInt(2, (oldQty-DBConnect.rs.getInt("quantity")));
                        st.setInt(3, 0);
                        st.setInt(4, DBConnect.rs.getInt("quantity"));
                        st.setString(5, "OUT");
                        st.setString(6, "SOLD");
                        st.setString(7, date);
                        st.executeUpdate();

                        sql="update inventory set qty=? where productID=?";
                        st=DBConnect.con.prepareStatement(sql);
                        st.setInt(1, (oldQty-DBConnect.rs.getInt("quantity")));
                        st.setString(2, DBConnect.rs.getString("ID"));
                        st.executeUpdate();
                    }
                    
                }
                DBConnect.con.commit();
                JOptionPane.showMessageDialog(CustInfo.this, "Transaction Completed Succesfully","Success!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-199-ok-circle.png")));
                //Try to print a reciept
                int b=JOptionPane.showConfirmDialog(CustInfo.this, "Print sales reciept?","Confirmation!",JOptionPane.YES_NO_OPTION);
                this.dispose();
                main.unblur();
                if(b==0){   
                    try{
                        PrinterJob prnJob = PrinterJob.getPrinterJob();
                        prnJob.setPrintable(new PrintingReciept(CustInfo.this));
                        if (!prnJob.printDialog()){
                            main.refresh();
                                return;
                        }
                        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        prnJob.print();
                        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    }
                    catch (PrinterException ex) {
                            System.out.println("Printing error: " + ex.toString());
                    }
                }
                main.refresh();
            }catch(SQLException ex){
                try{
                    JOptionPane.showMessageDialog(CustInfo.this, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    System.out.println(ex.getMessage());
                    DBConnect.con.rollback();
                }catch(SQLException sqlEx){

                }
            }finally{
                try{
                    DBConnect.con.setAutoCommit(true);
                }catch(SQLException sqlEx){

                }
            }
        }
    }//GEN-LAST:event_completeActionPerformed
    public String getName(){
        return this.custName.getText().toUpperCase();
    }
    
    public String getNumber(){
        return this.custNumber.getText();
    }
    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustInfo dialog = new CustInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton complete;
    private javax.swing.JTextField custName;
    private javax.swing.JTextField custNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel uDemo14;
    private javax.swing.JLabel uDemo16;
    // End of variables declaration//GEN-END:variables
}
