/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import com.dataStructures.MyContainer;
import com.dataStructures.MyVisitor;
import static com.main.MainMenuTest.contentPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author NUHU
 */
public class EditProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    public EditProduct(Options main) {
        initComponents();
        this.main=main;
    }
    Options main;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uDemo16 = new javax.swing.JLabel();
        validateID = new javax.swing.JButton();
        productID = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();
        uDemo18 = new javax.swing.JLabel();
        uDemo14 = new javax.swing.JLabel();
        productID1 = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        uDemo15 = new javax.swing.JLabel();
        charge = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(360, 347));
        setPreferredSize(new java.awt.Dimension(780, 351));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EDIT DRUG INFORMATION");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 550, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 12, 92)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("Drug ID");
        jPanel2.add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        validateID.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validateID.setText("Validate ID");
        validateID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateIDActionPerformed(evt);
            }
        });
        jPanel2.add(validateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, 35));

        productID.setBackground(new java.awt.Color(204, 204, 255));
        productID.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 460, 100));

        cancel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cancel.setText("Close");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, 35));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update Product");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 190, 35));

        uDemo18.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo18.setForeground(new java.awt.Color(0, 0, 102));
        uDemo18.setText("Drug ID");
        add(uDemo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        uDemo14.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo14.setForeground(new java.awt.Color(0, 0, 102));
        uDemo14.setText("Drug Name");
        add(uDemo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));

        productID1.setEditable(false);
        productID1.setBackground(new java.awt.Color(204, 204, 255));
        productID1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productID1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(productID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 380, -1));

        productName.setBackground(new java.awt.Color(204, 204, 255));
        productName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 380, -1));

        uDemo15.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo15.setForeground(new java.awt.Color(0, 0, 102));
        uDemo15.setText("Charge");
        add(uDemo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 30));

        charge.setBackground(new java.awt.Color(204, 204, 255));
        charge.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        charge.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 380, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        MainMenuTest.contentPanel.removeAll();
        MainMenuTest.contentPanel.setVisible(false);
        MainMenuTest.contentPanel.setVisible(true);
        
        main.refresh();
    }//GEN-LAST:event_cancelActionPerformed

    public String ucfirst(String s){
        try{
            String first, second;
            first=s.substring(0,1);
            second=s.substring(1);
            return first.toUpperCase()+second.toLowerCase();
        }catch(Exception ex){
            return "";
        }
    }
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String productID1=this.productID1.getText().trim();
        String productName=this.productName.getText().trim();
        String charge= this.charge.getText().trim();
        
        productID1=ucfirst(productID1);
        productName=ucfirst(productName);
        charge= ucfirst(charge);
        
        MyContainer c= new MyContainer();
        
        String patProductID = "^[a-zA-Z0-9]{6}$";
        String patProductName = "^[a-zA-Z0-9].{3,30}$";
        String patCharge = "^(([1-9](\\d*|\\d{0,2}(,\\d{3})*))|0)(\\.\\d{1,2})?";
 
        if(!Pattern.matches(patProductID, productID1)){
            c.insert("Invalid Drug ID");
        }
        if(!Pattern.matches(patProductName, productName)){
            c.insert("Invalid Drug Name");
        }
        if(!Pattern.matches(patCharge, charge)){
            c.insert("Invalid Charge Amount");
        }
        
        if(this.productID1.getText().equals("") || this.productName.getText().equals("") || this.charge.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Fields","Error!",JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else if(c.getCount()!=0){
            MyVisitor v= new MyVisitor();
            c.accept(v);
            
            JOptionPane.showMessageDialog(null,v.getErrors(), "Error!", JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                //Update the info
                PreparedStatement st;
                String sql="update product set productName=?, charge=? where productID=?";
                st= DBConnect.con.prepareStatement(sql);
                st.setString(1, productName);
                st.setString(2, charge);
                st.setString(3, productID1);
                st.executeUpdate();

                JOptionPane.showMessageDialog(null, "Information Updated","Success!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-199-ok-circle.png")));
                //Refresh page
                refresh();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Issue excecuting query","Issue!", JOptionPane.OK_OPTION);
            }finally{
                c.purge();
                DBConnect.rs=null;
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditProduct editForm = new EditProduct(main);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
                try {
                    contentPanel.setVisible(false);
                    contentPanel.setVisible(true);
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(null, e.getMessage());
                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        runner.start();
    }
    
    private void validateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateIDActionPerformed
        String productID=this.productID.getText().trim();
        
        String patProductID = "^[a-zA-Z0-9]{6}$";
        if(!Pattern.matches(patProductID, productID)){
            JOptionPane.showMessageDialog(null, "Invalid Drug ID","Issue!",JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql="select * from product where productID=?";
                st=DBConnect.con.prepareStatement(sql);
                st.setString(1, productID);
                DBConnect.rs=st.executeQuery();
                if(DBConnect.rs.next()){
                    productID1.setText(DBConnect.rs.getString(1));
                    productName.setText(DBConnect.rs.getString(2));
                    charge.setText(DBConnect.rs.getString(3));
                }else{
                    JOptionPane.showMessageDialog(null, "Drug ID does not exist","Issue!", JOptionPane.OK_OPTION);
                    productID1.setText("");
                    productName.setText("");
                    charge.setText("");
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(null, "Issues excecuting query","Issue!", JOptionPane.OK_OPTION);
                productID1.setText("");
                productName.setText("");
                charge.setText("");
            }
        }        
    }//GEN-LAST:event_validateIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField charge;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productID1;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel uDemo14;
    private javax.swing.JLabel uDemo15;
    private javax.swing.JLabel uDemo16;
    private javax.swing.JLabel uDemo18;
    private javax.swing.JButton update;
    private javax.swing.JButton validateID;
    // End of variables declaration//GEN-END:variables
}
