/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import com.dataStructures.MyContainer;
import com.dataStructures.MyVisitor;
import static com.main.MainMenuTest.contentPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author NUHU
 */
public class EditService extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    Options main;
    public EditService(Options main) {
        this.main=main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uDemo16 = new javax.swing.JLabel();
        validateID = new javax.swing.JButton();
        serviceID = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();
        uDemo19 = new javax.swing.JLabel();
        uDemo14 = new javax.swing.JLabel();
        serviceID1 = new javax.swing.JTextField();
        serviceName = new javax.swing.JTextField();
        uDemo15 = new javax.swing.JLabel();
        chargeRegular = new javax.swing.JTextField();
        uDemo17 = new javax.swing.JLabel();
        chargeHome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(360, 347));
        setPreferredSize(new java.awt.Dimension(758, 391));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EDIT SERVICE INFORMATION");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 740, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 12, 92)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("Service ID");
        jPanel2.add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        validateID.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validateID.setText("Validate ID");
        validateID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateIDActionPerformed(evt);
            }
        });
        jPanel2.add(validateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, 35));

        serviceID.setBackground(new java.awt.Color(204, 204, 255));
        serviceID.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        serviceID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        serviceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceIDActionPerformed(evt);
            }
        });
        jPanel2.add(serviceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 460, 100));

        cancel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cancel.setText("Close");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 90, 35));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update Service");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 190, 35));

        uDemo19.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo19.setForeground(new java.awt.Color(0, 0, 102));
        uDemo19.setText("Service ID");
        add(uDemo19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        uDemo14.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo14.setForeground(new java.awt.Color(0, 0, 102));
        uDemo14.setText("Service Name");
        add(uDemo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 30));

        serviceID1.setEditable(false);
        serviceID1.setBackground(new java.awt.Color(204, 204, 255));
        serviceID1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        serviceID1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(serviceID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 310, -1));

        serviceName.setBackground(new java.awt.Color(204, 204, 255));
        serviceName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        serviceName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(serviceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 310, -1));

        uDemo15.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo15.setForeground(new java.awt.Color(0, 0, 102));
        uDemo15.setText("Charge (Regular)");
        add(uDemo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 30));

        chargeRegular.setBackground(new java.awt.Color(204, 204, 255));
        chargeRegular.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        chargeRegular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(chargeRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 310, -1));

        uDemo17.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo17.setForeground(new java.awt.Color(0, 0, 102));
        uDemo17.setText("Charge (Home Serving)");
        add(uDemo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, 30));

        chargeHome.setBackground(new java.awt.Color(204, 204, 255));
        chargeHome.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        chargeHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(chargeHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        MainMenuTest.contentPanel.removeAll();
        MainMenuTest.contentPanel.setVisible(false);
        MainMenuTest.contentPanel.setVisible(true);
        
        main.refresh();
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String serviceID1=this.serviceID1.getText().trim();
        String serviceName=this.serviceName.getText().trim();
        String chargeRegular= this.chargeRegular.getText().trim();
        String chargeHome= this.chargeHome.getText().trim();
        
        serviceName=ucfirst(serviceName);
        serviceID1= serviceID1.toUpperCase();
        
        MyContainer c= new MyContainer();
        
        String patServiceID = "^[a-zA-Z0-9]{6}$";
        String patServiceName = "^[a-zA-Z0-9].{3,30}$";
        String patCharge = "^(([1-9](\\d*|\\d{0,2}(,\\d{3})*))|0)(\\.\\d{1,2})?";
 
        if(!Pattern.matches(patServiceID, serviceID1)){
            c.insert("Invalid Service ID");
        }
        if(!Pattern.matches(patServiceName, serviceName)){
            c.insert("Invalid Service Name");
        }
        if(!Pattern.matches(patCharge, chargeHome)){
            c.insert("Invalid Home Charge Amount");
        }
        if(!Pattern.matches(patCharge, chargeRegular)){
            c.insert("Invalid Regular Charge Amount");
        }
        
        if(this.serviceID1.getText().equals("") || this.serviceName.getText().equals("") || this.chargeHome.getText().equals("")|| this.chargeRegular.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Fields","Error!",JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else if(c.getCount()!=0){
            MyVisitor v= new MyVisitor();
            c.accept(v);
            
            JOptionPane.showMessageDialog(null,v.getErrors(), "Error!", JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                //Update the info
                PreparedStatement st;
                String sql="update service set serviceName=?, chargeRegular=?, chargeHome=? where serviceID=?";
                st= DBConnect.con.prepareStatement(sql);
                st.setString(1, serviceName);
                st.setDouble(2, Double.parseDouble(chargeRegular));
                st.setDouble(3, Double.parseDouble(chargeHome));
                st.setString(4, serviceID1);
                st.executeUpdate();

                JOptionPane.showMessageDialog(null, "Information Updated","Success!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-199-ok-circle.png")));
                //Refresh page
                refresh();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Issue excecuting query","Issue!", JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
            }finally{
                c.purge();
                DBConnect.rs=null;
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditProduct editForm = new EditProduct(main);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
                try {
                    contentPanel.setVisible(false);
                    contentPanel.setVisible(true);
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(null, e.getMessage());
                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                }
            }
        };
        runner.start();
    }
    
    private void validateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateIDActionPerformed
        String serviceID=this.serviceID.getText().trim();
        
        String patServiceID = "^[a-zA-Z0-9]{6}$";
        if(!Pattern.matches(patServiceID, serviceID)){
            JOptionPane.showMessageDialog(null, "Invalid Service ID","Issue!",JOptionPane.OK_OPTION,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                PreparedStatement st;
                String sql="select * from service where serviceID=?";
                st=DBConnect.con.prepareStatement(sql);
                st.setString(1, serviceID);
                DBConnect.rs=st.executeQuery();
                if(DBConnect.rs.next()){
                    serviceID1.setText(DBConnect.rs.getString(1));
                    serviceName.setText(DBConnect.rs.getString(2));
                    chargeRegular.setText(DBConnect.rs.getString(3));
                    chargeHome.setText(DBConnect.rs.getString(4));
                }else{
                    JOptionPane.showMessageDialog(null, "Service ID does not exist","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    serviceID1.setText("");
                    serviceName.setText("");
                    chargeRegular.setText("");
                    chargeHome.setText("");
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(null, "Issues excecuting query","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                serviceID1.setText("");
                serviceName.setText("");
                chargeRegular.setText("");
                chargeHome.setText("");
            }
        }        
    }//GEN-LAST:event_validateIDActionPerformed
    
    public String ucfirst(String s){
        try{
            String first, second;
            first=s.substring(0,1);
            second=s.substring(1);
            return first.toUpperCase()+second.toLowerCase();
        }catch(Exception ex){
            return "";
        }
    }
    
    private void serviceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField chargeHome;
    private javax.swing.JTextField chargeRegular;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField serviceID;
    private javax.swing.JTextField serviceID1;
    private javax.swing.JTextField serviceName;
    private javax.swing.JLabel uDemo14;
    private javax.swing.JLabel uDemo15;
    private javax.swing.JLabel uDemo16;
    private javax.swing.JLabel uDemo17;
    private javax.swing.JLabel uDemo19;
    private javax.swing.JButton update;
    private javax.swing.JButton validateID;
    // End of variables declaration//GEN-END:variables
}
