/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Nuhu Ibrahim
 */
public class LoginPage extends javax.swing.JPanel {

    /**
     * Creates new form LoginPage1
     */
    
    MainMenuTest main;
    public LoginPage(MainMenuTest main) {
        this.main=main;
        initComponents();
    }

    String usertype="";
    String surname, othernames="";
    public static String user="";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setNextFocusableComponent(username);
        setPreferredSize(new java.awt.Dimension(657, 409));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 102));
        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        password.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        password.setText("n");
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 300, 35));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Sign-In");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 40));

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        message.setForeground(new java.awt.Color(0, 0, 102));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Validating User...");
        add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 510, 40));

        username.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        username.setText("n");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        username.setNextFocusableComponent(password);
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 300, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/banner2.jpg"))); // NOI18N
        jLabel1.setIconTextGap(0);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(username.getText()) || "".equals(password.getText())){
            //JOptionPane.showMessageDialog(this,"Empty fields, try again","Empty Field", JOptionPane.OK_OPTION);
            message.setForeground(Color.red);
            message.setText("Empty fields, try again");
            message.setVisible(true);
        }else{
            Thread runner = new Thread() {
                public void run() {
                    message.setForeground(new java.awt.Color(255, 255, 255));
                    message.setText("Validating User...");
                    try {
                        message.setVisible(true);
                        //iconm.setVisible(true);
                        Thread.sleep(3000);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    }
                    String pass="";

                    try{
                        String sql1= "select * from Usertbl where Uname='"+username.getText()+"'";
                        DBConnect.rs= DBConnect.st.executeQuery(sql1);
                        if(DBConnect.rs.next()){
                            pass=DBConnect.rs.getString("pword");
                            user=DBConnect.rs.getString("Uname");
                            //usertype=DBConnect.rs.getString("Usertype");
                            //surname=DBConnect.rs.getString("Surname");
                            //othernames=DBConnect.rs.getString("Othernames");
                        }
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage());
                        JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    }
                    if (pass.equals(password.getText()) && user.equalsIgnoreCase(username.getText()) ){
                        Thread runner2 = new Thread() {
                            public void run() {
                                message.setForeground(new java.awt.Color(255, 255, 255));
                                message.setText("Login Successful, Loading...");
                                try {
                                    message.setVisible(true);
                                    //iconm.setVisible(true);
                                    Thread.sleep(6000);
                                    userControlsTest();
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                                }
                            }
                        };
                        runner2.start();
                    }
                    else{
                        //iconm.setVisible(false);
                        message.setForeground(Color.red);
                        message.setText("Invalid Login Details, try again.");
                    }
                }
            };
            runner.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void userControlsTest(){
        Options op= new Options(main);
        
        JScrollPane scrollPane;
        scrollPane = new JScrollPane(op);
        MainMenuTest.optionPanel.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 400));
        
        MainMenuTest.contentPanel.removeAll();
        MainMenuTest.contentPanel.setVisible(false);
        MainMenuTest.contentPanel.setVisible(true);
        MainMenuTest.jPanel2.setVisible(true);
        MainMenuTest.jPanel1.setVisible(true);
        MainMenuTest.optionPanel.setVisible(true);
        
        //setting Tree  User invisible
        MainMenuTest.optionPanel.setVisible(false);
        MainMenuTest.optionPanel.setVisible(true);
        MainMenuTest.contentPanel.setBackground(Color.WHITE);
        MainMenuTest.desktop1.setBackground(Color.WHITE);
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel message;
    private javax.swing.JPasswordField password;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
