/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import static com.main.MainMenuTest.contentPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JLayer;
import javax.swing.JOptionPane;

/**
 *
 * @author Nuhu Ibrahim
 */
public class Options extends javax.swing.JPanel {

    /**
     * Creates new form Options
     */
    MainMenuTest main;
    public Options(MainMenuTest main) {
        this.main=main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servPnl = new javax.swing.JPanel();
        servBtn = new javax.swing.JButton();
        prodPnl = new javax.swing.JPanel();
        prodBtn = new javax.swing.JButton();
        optionPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        addProductPnl = new javax.swing.JPanel();
        addProductBtn = new javax.swing.JButton();
        editProductPnl = new javax.swing.JPanel();
        editProductBtn = new javax.swing.JButton();
        addServicePnl = new javax.swing.JPanel();
        addServiceBtn = new javax.swing.JButton();
        editServicePnl = new javax.swing.JPanel();
        editServiceBtn = new javax.swing.JButton();
        inventoryPnl = new javax.swing.JPanel();
        inventoryBtn = new javax.swing.JButton();
        removeDefectPnl = new javax.swing.JPanel();
        removeDefectBtn = new javax.swing.JButton();
        perdormSalesPnl = new javax.swing.JPanel();
        perdormSalesBtn = new javax.swing.JButton();
        invenoryReportPnl = new javax.swing.JPanel();
        invenoryReportBtn = new javax.swing.JButton();
        inventoryTrackPnl = new javax.swing.JPanel();
        inventoryTrackBtn = new javax.swing.JButton();
        salesReportPnl = new javax.swing.JPanel();
        salesReportBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        servPnl.setBackground(new java.awt.Color(255, 255, 255));
        servPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        servBtn.setBackground(new java.awt.Color(255, 255, 255));
        servBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        servBtn.setForeground(new java.awt.Color(102, 102, 102));
        servBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-530-list-alt.png"))); // NOI18N
        servBtn.setText("View all Services");
        servBtn.setBorder(null);
        servBtn.setBorderPainted(false);
        servBtn.setContentAreaFilled(false);
        servBtn.setFocusPainted(false);
        servBtn.setFocusable(false);
        servBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        servBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        servBtn.setRequestFocusEnabled(false);
        servBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                servBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                servBtnMouseExited(evt);
            }
        });
        servBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servBtnActionPerformed(evt);
            }
        });
        servPnl.add(servBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        add(servPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 440, 225, -1));

        prodPnl.setBackground(new java.awt.Color(255, 255, 255));
        prodPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prodBtn.setBackground(new java.awt.Color(255, 255, 255));
        prodBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        prodBtn.setForeground(new java.awt.Color(102, 102, 102));
        prodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-530-list-alt.png"))); // NOI18N
        prodBtn.setText("View all Drugs");
        prodBtn.setBorder(null);
        prodBtn.setBorderPainted(false);
        prodBtn.setContentAreaFilled(false);
        prodBtn.setFocusPainted(false);
        prodBtn.setFocusable(false);
        prodBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prodBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        prodBtn.setRequestFocusEnabled(false);
        prodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prodBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prodBtnMouseExited(evt);
            }
        });
        prodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodBtnActionPerformed(evt);
            }
        });
        prodPnl.add(prodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        add(prodPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 400, 225, -1));

        optionPanel.setBackground(new java.awt.Color(184, 184, 235));
        optionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        optionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        optionPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 0, 10, 500));

        addProductPnl.setBackground(new java.awt.Color(255, 255, 255));
        addProductPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addProductBtn.setBackground(new java.awt.Color(255, 255, 255));
        addProductBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addProductBtn.setForeground(new java.awt.Color(102, 102, 102));
        addProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-703-file-plus.png"))); // NOI18N
        addProductBtn.setText("Add Drug");
        addProductBtn.setBorder(null);
        addProductBtn.setBorderPainted(false);
        addProductBtn.setContentAreaFilled(false);
        addProductBtn.setFocusPainted(false);
        addProductBtn.setFocusable(false);
        addProductBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addProductBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        addProductBtn.setRequestFocusEnabled(false);
        addProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addProductBtnMouseExited(evt);
            }
        });
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });
        addProductPnl.add(addProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(addProductPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 225, -1));

        editProductPnl.setBackground(new java.awt.Color(255, 255, 255));
        editProductPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editProductBtn.setBackground(new java.awt.Color(255, 255, 255));
        editProductBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        editProductBtn.setForeground(new java.awt.Color(102, 102, 102));
        editProductBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-151-edit.png"))); // NOI18N
        editProductBtn.setText("Edit Drug");
        editProductBtn.setBorder(null);
        editProductBtn.setBorderPainted(false);
        editProductBtn.setContentAreaFilled(false);
        editProductBtn.setFocusPainted(false);
        editProductBtn.setFocusable(false);
        editProductBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editProductBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        editProductBtn.setRequestFocusEnabled(false);
        editProductBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProductBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProductBtnMouseExited(evt);
            }
        });
        editProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductBtnActionPerformed(evt);
            }
        });
        editProductPnl.add(editProductBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(editProductPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 40, 225, -1));

        addServicePnl.setBackground(new java.awt.Color(255, 255, 255));
        addServicePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addServiceBtn.setBackground(new java.awt.Color(255, 255, 255));
        addServiceBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addServiceBtn.setForeground(new java.awt.Color(102, 102, 102));
        addServiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-703-file-plus.png"))); // NOI18N
        addServiceBtn.setText("Add Service");
        addServiceBtn.setBorder(null);
        addServiceBtn.setBorderPainted(false);
        addServiceBtn.setContentAreaFilled(false);
        addServiceBtn.setFocusPainted(false);
        addServiceBtn.setFocusable(false);
        addServiceBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addServiceBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        addServiceBtn.setRequestFocusEnabled(false);
        addServiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addServiceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addServiceBtnMouseExited(evt);
            }
        });
        addServiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServiceBtnActionPerformed(evt);
            }
        });
        addServicePnl.add(addServiceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(addServicePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, 225, -1));

        editServicePnl.setBackground(new java.awt.Color(255, 255, 255));
        editServicePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editServiceBtn.setBackground(new java.awt.Color(255, 255, 255));
        editServiceBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        editServiceBtn.setForeground(new java.awt.Color(102, 102, 102));
        editServiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-151-edit.png"))); // NOI18N
        editServiceBtn.setText("Edit Service");
        editServiceBtn.setBorder(null);
        editServiceBtn.setBorderPainted(false);
        editServiceBtn.setContentAreaFilled(false);
        editServiceBtn.setFocusPainted(false);
        editServiceBtn.setFocusable(false);
        editServiceBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        editServiceBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        editServiceBtn.setRequestFocusEnabled(false);
        editServiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editServiceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editServiceBtnMouseExited(evt);
            }
        });
        editServiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editServiceBtnActionPerformed(evt);
            }
        });
        editServicePnl.add(editServiceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(editServicePnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 120, 225, -1));

        inventoryPnl.setBackground(new java.awt.Color(255, 255, 255));
        inventoryPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventoryBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        inventoryBtn.setForeground(new java.awt.Color(102, 102, 102));
        inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-146-folder-plus.png"))); // NOI18N
        inventoryBtn.setText("Add to Stock");
        inventoryBtn.setBorder(null);
        inventoryBtn.setBorderPainted(false);
        inventoryBtn.setContentAreaFilled(false);
        inventoryBtn.setFocusPainted(false);
        inventoryBtn.setFocusable(false);
        inventoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        inventoryBtn.setRequestFocusEnabled(false);
        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseExited(evt);
            }
        });
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });
        inventoryPnl.add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(inventoryPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 160, 225, -1));

        removeDefectPnl.setBackground(new java.awt.Color(255, 255, 255));
        removeDefectPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeDefectBtn.setBackground(new java.awt.Color(255, 255, 255));
        removeDefectBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        removeDefectBtn.setForeground(new java.awt.Color(102, 102, 102));
        removeDefectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-17-bin.png"))); // NOI18N
        removeDefectBtn.setText("Remove Defects");
        removeDefectBtn.setBorder(null);
        removeDefectBtn.setBorderPainted(false);
        removeDefectBtn.setContentAreaFilled(false);
        removeDefectBtn.setFocusPainted(false);
        removeDefectBtn.setFocusable(false);
        removeDefectBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removeDefectBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        removeDefectBtn.setRequestFocusEnabled(false);
        removeDefectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeDefectBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeDefectBtnMouseExited(evt);
            }
        });
        removeDefectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDefectBtnActionPerformed(evt);
            }
        });
        removeDefectPnl.add(removeDefectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(removeDefectPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 200, 225, -1));

        perdormSalesPnl.setBackground(new java.awt.Color(255, 255, 255));
        perdormSalesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perdormSalesBtn.setBackground(new java.awt.Color(255, 255, 255));
        perdormSalesBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        perdormSalesBtn.setForeground(new java.awt.Color(102, 102, 102));
        perdormSalesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-203-shopping-cart.png"))); // NOI18N
        perdormSalesBtn.setText("Perform Sales");
        perdormSalesBtn.setBorder(null);
        perdormSalesBtn.setBorderPainted(false);
        perdormSalesBtn.setContentAreaFilled(false);
        perdormSalesBtn.setFocusPainted(false);
        perdormSalesBtn.setFocusable(false);
        perdormSalesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perdormSalesBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        perdormSalesBtn.setRequestFocusEnabled(false);
        perdormSalesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perdormSalesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perdormSalesBtnMouseExited(evt);
            }
        });
        perdormSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdormSalesBtnActionPerformed(evt);
            }
        });
        perdormSalesPnl.add(perdormSalesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(perdormSalesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 240, 225, -1));

        invenoryReportPnl.setBackground(new java.awt.Color(255, 255, 255));
        invenoryReportPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invenoryReportBtn.setBackground(new java.awt.Color(255, 255, 255));
        invenoryReportBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        invenoryReportBtn.setForeground(new java.awt.Color(102, 102, 102));
        invenoryReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-517-menu-hamburger.png"))); // NOI18N
        invenoryReportBtn.setText("Inventory Report");
        invenoryReportBtn.setBorder(null);
        invenoryReportBtn.setBorderPainted(false);
        invenoryReportBtn.setContentAreaFilled(false);
        invenoryReportBtn.setFocusPainted(false);
        invenoryReportBtn.setFocusable(false);
        invenoryReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invenoryReportBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        invenoryReportBtn.setRequestFocusEnabled(false);
        invenoryReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                invenoryReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                invenoryReportBtnMouseExited(evt);
            }
        });
        invenoryReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invenoryReportBtnActionPerformed(evt);
            }
        });
        invenoryReportPnl.add(invenoryReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(invenoryReportPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 280, 225, -1));

        inventoryTrackPnl.setBackground(new java.awt.Color(255, 255, 255));
        inventoryTrackPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTrackBtn.setBackground(new java.awt.Color(255, 255, 255));
        inventoryTrackBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        inventoryTrackBtn.setForeground(new java.awt.Color(102, 102, 102));
        inventoryTrackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-87-display.png"))); // NOI18N
        inventoryTrackBtn.setText("Inventory Track");
        inventoryTrackBtn.setBorder(null);
        inventoryTrackBtn.setBorderPainted(false);
        inventoryTrackBtn.setContentAreaFilled(false);
        inventoryTrackBtn.setFocusPainted(false);
        inventoryTrackBtn.setFocusable(false);
        inventoryTrackBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryTrackBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        inventoryTrackBtn.setRequestFocusEnabled(false);
        inventoryTrackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryTrackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryTrackBtnMouseExited(evt);
            }
        });
        inventoryTrackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryTrackBtnActionPerformed(evt);
            }
        });
        inventoryTrackPnl.add(inventoryTrackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(inventoryTrackPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 320, 225, -1));

        salesReportPnl.setBackground(new java.awt.Color(255, 255, 255));
        salesReportPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salesReportBtn.setBackground(new java.awt.Color(255, 255, 255));
        salesReportBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        salesReportBtn.setForeground(new java.awt.Color(102, 102, 102));
        salesReportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-517-menu-hamburger.png"))); // NOI18N
        salesReportBtn.setText("Sales Report");
        salesReportBtn.setBorder(null);
        salesReportBtn.setBorderPainted(false);
        salesReportBtn.setContentAreaFilled(false);
        salesReportBtn.setFocusPainted(false);
        salesReportBtn.setFocusable(false);
        salesReportBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salesReportBtn.setMargin(new java.awt.Insets(14, 28, 14, 14));
        salesReportBtn.setRequestFocusEnabled(false);
        salesReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesReportBtnMouseExited(evt);
            }
        });
        salesReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesReportBtnActionPerformed(evt);
            }
        });
        salesReportPnl.add(salesReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        optionPanel.add(salesReportPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 360, 225, -1));

        add(optionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 482));
    }// </editor-fold>//GEN-END:initComponents
    
    public void blur(){
        c=main.getContentPane();
        JLayer<Component> blurLayer = new JLayer<>(main.getContentPane(), new BlurLayerUI());
        main.setContentPane(blurLayer);
        main.setVisible(false);
        main.setVisible(true);
    }
    public void unblur(){
        main.setContentPane(c);
    }
    public Container c;
    public void refresh(){
        //For Add Product Button
        addProductPnl.setBackground(oldC);
        addProductPnl.setVisible(false);
        addProductPnl.setVisible(true);
        addProductSnl=false;
        
        //For Edit Product Button
        editProductPnl.setBackground(oldC);
        editProductPnl.setVisible(false);
        editProductPnl.setVisible(true);
        editProductSnl=false;
        
        //For Add Service Button
        addServicePnl.setBackground(oldC);
        addServicePnl.setVisible(false);
        addServicePnl.setVisible(true);
        addServiceSnl=false;
        
        //For Edit Service Button
        editServicePnl.setBackground(oldC);
        editServicePnl.setVisible(false);
        editServicePnl.setVisible(true);
        editServiceSnl=false;
        
        //For Inventory Button
        inventoryPnl.setBackground(oldC);
        inventoryPnl.setVisible(false);
        inventoryPnl.setVisible(true);
        inventorySnl=false;
        
        //For Defected Button
        removeDefectPnl.setBackground(oldC);
        removeDefectPnl.setVisible(false);
        removeDefectPnl.setVisible(true);
        removeDefectSnl=false;
        
        //For Perform Sales Button
        perdormSalesPnl.setBackground(oldC);
        perdormSalesPnl.setVisible(false);
        perdormSalesPnl.setVisible(true);
        perdormSalesSnl=false;
        
        //For Inventory Report Button
        invenoryReportPnl.setBackground(oldC);
        invenoryReportPnl.setVisible(false);
        invenoryReportPnl.setVisible(true);
        invenoryReportSnl=false;
        
        //For Sales Report Button
        salesReportPnl.setBackground(oldC);
        salesReportPnl.setVisible(false);
        salesReportPnl.setVisible(true);
        salesReportSnl=false;
        
        //For Services Button
        servPnl.setBackground(oldC);
        servPnl.setVisible(false);
        servPnl.setVisible(true);
        prodServSnl=false;
        
        //For Products Button
        prodPnl.setBackground(oldC);
        prodPnl.setVisible(false);
        prodPnl.setVisible(true);
        prodSnl=false;
        
        //For Inventory Track Button Button
        inventoryTrackPnl.setBackground(oldC);
        inventoryTrackPnl.setVisible(false);
        inventoryTrackPnl.setVisible(true);
        inventoryTrackSnl=false;
        
    }
    boolean addProductSnl=false;
    boolean editProductSnl=false;
    boolean addServiceSnl=false;   
    boolean editServiceSnl=false;
    boolean inventorySnl=false;    
    boolean removeDefectSnl=false;    
    boolean perdormSalesSnl;    
    boolean invenoryReportSnl;    
    boolean salesReportSnl;    
    boolean prodServSnl;
    
    private Color oldC=new Color(184,184,235);
    private Color newC= new Color(204,204,255);
    
    private void addProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseEntered
        if(addProductSnl){
            //Do nothing
        }else{
            addProductPnl.setBackground(newC);
            addProductPnl.setVisible(false);
            addProductPnl.setVisible(true);
        }
    }//GEN-LAST:event_addProductBtnMouseEntered

    private void addProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductBtnMouseExited
        if(addProductSnl){
            //Do nothing
        }else{
            addProductPnl.setBackground(oldC);
            addProductPnl.setVisible(false);
            addProductPnl.setVisible(true);
        }
    }//GEN-LAST:event_addProductBtnMouseExited

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        addProductSnl=true;
        addProductPnl.setBackground(Color.WHITE);
        addProductPnl.setVisible(false);
        addProductPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                AddProduct editForm = new AddProduct(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_addProductBtnActionPerformed
    public MainMenuTest getMenu(){
        return main;
    }
    private void editProductBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProductBtnMouseEntered
        if(editProductSnl){
            //Do nothing
        }else{
            editProductPnl.setBackground(newC);
            editProductPnl.setVisible(false);
            editProductPnl.setVisible(true);
        }
    }//GEN-LAST:event_editProductBtnMouseEntered

    private void editProductBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProductBtnMouseExited
        if(editProductSnl){
            //Do nothing
        }else{
            editProductPnl.setBackground(oldC);
            editProductPnl.setVisible(false);
            editProductPnl.setVisible(true);
        }
    }//GEN-LAST:event_editProductBtnMouseExited

    private void editProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        editProductSnl=true;
        editProductPnl.setBackground(Color.WHITE);
        editProductPnl.setVisible(false);
        editProductPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                EditProduct editForm = new EditProduct(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_editProductBtnActionPerformed

    private void addServiceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addServiceBtnMouseEntered
        if(addServiceSnl){
            //Do nothing
        }else{
            addServicePnl.setBackground(newC);
            addServicePnl.setVisible(false);
            addServicePnl.setVisible(true);
        }
    }//GEN-LAST:event_addServiceBtnMouseEntered

    private void addServiceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addServiceBtnMouseExited
        if(addServiceSnl){
            //Do nothing
        }else{
            addServicePnl.setBackground(oldC);
            addServicePnl.setVisible(false);
            addServicePnl.setVisible(true);
        }
    }//GEN-LAST:event_addServiceBtnMouseExited

    private void addServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        addServiceSnl=true;
        addServicePnl.setBackground(Color.WHITE);
        addServicePnl.setVisible(false);
        addServicePnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                AddService editForm = new AddService(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_addServiceBtnActionPerformed

    private void editServiceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editServiceBtnMouseEntered
        if(editServiceSnl){
            //Do nothing
        }else{
            editServicePnl.setBackground(newC);
            editServicePnl.setVisible(false);
            editServicePnl.setVisible(true);
        }
    }//GEN-LAST:event_editServiceBtnMouseEntered

    private void editServiceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editServiceBtnMouseExited
        if(editServiceSnl){
            //Do nothing
        }else{
            editServicePnl.setBackground(oldC);
            editServicePnl.setVisible(false);
            editServicePnl.setVisible(true);
        }
    }//GEN-LAST:event_editServiceBtnMouseExited

    private void editServiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editServiceBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        editServiceSnl=true;
        editServicePnl.setBackground(Color.WHITE);
        editServicePnl.setVisible(false);
        editServicePnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                EditService editForm = new EditService(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_editServiceBtnActionPerformed

    private void inventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseEntered
        if(inventorySnl){
            //Do nothing
        }else{
            inventoryPnl.setBackground(newC);
            inventoryPnl.setVisible(false);
            inventoryPnl.setVisible(true);
        }
    }//GEN-LAST:event_inventoryBtnMouseEntered

    private void inventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseExited
        if(inventorySnl){
            //Do nothing
        }else{
            inventoryPnl.setBackground(oldC);
            inventoryPnl.setVisible(false);
            inventoryPnl.setVisible(true);
        }
    }//GEN-LAST:event_inventoryBtnMouseExited

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        inventorySnl=true;
        inventoryPnl.setBackground(Color.WHITE);
        inventoryPnl.setVisible(false);
        inventoryPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                Inventory editForm = new Inventory(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void removeDefectBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeDefectBtnMouseEntered
        if(removeDefectSnl){
            //Do nothing
        }else{
            removeDefectPnl.setBackground(newC);
            removeDefectPnl.setVisible(false);
            removeDefectPnl.setVisible(true);
        }
    }//GEN-LAST:event_removeDefectBtnMouseEntered

    private void removeDefectBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeDefectBtnMouseExited
        if(removeDefectSnl){
            //Do nothing
        }else{
            removeDefectPnl.setBackground(oldC);
            removeDefectPnl.setVisible(false);
            removeDefectPnl.setVisible(true);
        }
    }//GEN-LAST:event_removeDefectBtnMouseExited

    private void removeDefectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDefectBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        removeDefectSnl=true;
        removeDefectPnl.setBackground(Color.WHITE);
        removeDefectPnl.setVisible(false);
        removeDefectPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                RemoveDefected editForm = new RemoveDefected(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_removeDefectBtnActionPerformed

    private void perdormSalesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perdormSalesBtnMouseEntered
        if(perdormSalesSnl){
            //Do nothing
        }else{
            perdormSalesPnl.setBackground(newC);
            perdormSalesPnl.setVisible(false);
            perdormSalesPnl.setVisible(true);
        }
    }//GEN-LAST:event_perdormSalesBtnMouseEntered

    private void perdormSalesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perdormSalesBtnMouseExited
        if(perdormSalesSnl){
            //Do nothing
        }else{
            perdormSalesPnl.setBackground(oldC);
            perdormSalesPnl.setVisible(false);
            perdormSalesPnl.setVisible(true);
        }
    }//GEN-LAST:event_perdormSalesBtnMouseExited

    private void perdormSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdormSalesBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        perdormSalesSnl=true;
        perdormSalesPnl.setBackground(Color.WHITE);
        perdormSalesPnl.setVisible(false);
        perdormSalesPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ProcessSales editForm = new ProcessSales(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_perdormSalesBtnActionPerformed

    private void invenoryReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invenoryReportBtnMouseEntered
        if(invenoryReportSnl){
            //Do nothing
        }else{
            invenoryReportPnl.setBackground(newC);
            invenoryReportPnl.setVisible(false);
            invenoryReportPnl.setVisible(true);
        }
    }//GEN-LAST:event_invenoryReportBtnMouseEntered

    private void invenoryReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invenoryReportBtnMouseExited
        if(invenoryReportSnl){
            //Do nothing
        }else{
            invenoryReportPnl.setBackground(oldC);
            invenoryReportPnl.setVisible(false);
            invenoryReportPnl.setVisible(true);
        }
    }//GEN-LAST:event_invenoryReportBtnMouseExited

    private void invenoryReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invenoryReportBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        invenoryReportSnl=true;
        invenoryReportPnl.setBackground(Color.WHITE);
        invenoryReportPnl.setVisible(false);
        invenoryReportPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ViewInventory editForm = new ViewInventory(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_invenoryReportBtnActionPerformed

    private void salesReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportBtnMouseEntered
        if(salesReportSnl){
            //Do nothing
        }else{
            salesReportPnl.setBackground(newC);
            salesReportPnl.setVisible(false);
            salesReportPnl.setVisible(true);
        }
    }//GEN-LAST:event_salesReportBtnMouseEntered

    private void salesReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesReportBtnMouseExited
        if(salesReportSnl){
            //Do nothing
        }else{
            salesReportPnl.setBackground(oldC);
            salesReportPnl.setVisible(false);
            salesReportPnl.setVisible(true);
        }
    }//GEN-LAST:event_salesReportBtnMouseExited

    private void salesReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesReportBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        salesReportSnl=true;
        salesReportPnl.setBackground(Color.WHITE);
        salesReportPnl.setVisible(false);
        salesReportPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ViewSalesInfo editForm = new ViewSalesInfo(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_salesReportBtnActionPerformed

    private void servBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servBtnMouseEntered
        if(prodServSnl){
            //Do nothing
        }else{
            servPnl.setBackground(newC);
            servPnl.setVisible(false);
            servPnl.setVisible(true);
        }
    }//GEN-LAST:event_servBtnMouseEntered

    private void servBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servBtnMouseExited
        if(prodServSnl){
            //Do nothing
        }else{
            servPnl.setBackground(oldC);
            servPnl.setVisible(false);
            servPnl.setVisible(true);
        }
    }//GEN-LAST:event_servBtnMouseExited

    private void servBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        prodServSnl=true;
        servPnl.setBackground(Color.WHITE);
        servPnl.setVisible(false);
        servPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ViewService editForm = new ViewService(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_servBtnActionPerformed
    boolean prodSnl;
    private void prodBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseEntered
        if(prodSnl){
            //Do nothing
        }else{
            prodPnl.setBackground(newC);
            prodPnl.setVisible(false);
            prodPnl.setVisible(true);
        }
    }//GEN-LAST:event_prodBtnMouseEntered

    private void prodBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodBtnMouseExited
        if(prodSnl){
            //Do nothing
        }else{
            prodPnl.setBackground(oldC);
            prodPnl.setVisible(false);
            prodPnl.setVisible(true);
        }
    }//GEN-LAST:event_prodBtnMouseExited

    private void prodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        prodSnl=true;
        prodPnl.setBackground(Color.WHITE);
        prodPnl.setVisible(false);
        prodPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ViewProduct editForm = new ViewProduct(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_prodBtnActionPerformed
    boolean inventoryTrackSnl;
    private void inventoryTrackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTrackBtnMouseEntered
        if(inventoryTrackSnl){
            //Do nothing
        }else{
            inventoryTrackPnl.setBackground(newC);
            inventoryTrackPnl.setVisible(false);
            inventoryTrackPnl.setVisible(true);
        }
    }//GEN-LAST:event_inventoryTrackBtnMouseEntered

    private void inventoryTrackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTrackBtnMouseExited
        if(inventoryTrackSnl){
            //Do nothing
        }else{
            inventoryTrackPnl.setBackground(oldC);
            inventoryTrackPnl.setVisible(false);
            inventoryTrackPnl.setVisible(true);
        }
    }//GEN-LAST:event_inventoryTrackBtnMouseExited

    private void inventoryTrackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryTrackBtnActionPerformed
        refresh(); //When refreshing, we change all backgrounds to normal and all selectedSigns to false
        inventoryTrackSnl=true;
        inventoryTrackPnl.setBackground(Color.WHITE);
        inventoryTrackPnl.setVisible(false);
        inventoryTrackPnl.setVisible(true);

        Thread runner = new Thread() {

            public void run() {
                ViewInventoryTrack editForm = new ViewInventoryTrack(Options.this);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
        try {
            contentPanel.setVisible(false);
            contentPanel.setVisible(true);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE,  new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }
        }
        };
        runner.start();
    }//GEN-LAST:event_inventoryTrackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBtn;
    private javax.swing.JPanel addProductPnl;
    private javax.swing.JButton addServiceBtn;
    private javax.swing.JPanel addServicePnl;
    private javax.swing.JButton editProductBtn;
    private javax.swing.JPanel editProductPnl;
    private javax.swing.JButton editServiceBtn;
    private javax.swing.JPanel editServicePnl;
    private javax.swing.JButton invenoryReportBtn;
    private javax.swing.JPanel invenoryReportPnl;
    private javax.swing.JButton inventoryBtn;
    private javax.swing.JPanel inventoryPnl;
    private javax.swing.JButton inventoryTrackBtn;
    private javax.swing.JPanel inventoryTrackPnl;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JPanel optionPanel;
    private javax.swing.JButton perdormSalesBtn;
    private javax.swing.JPanel perdormSalesPnl;
    private javax.swing.JButton prodBtn;
    private javax.swing.JPanel prodPnl;
    private javax.swing.JButton removeDefectBtn;
    private javax.swing.JPanel removeDefectPnl;
    private javax.swing.JButton salesReportBtn;
    private javax.swing.JPanel salesReportPnl;
    private javax.swing.JButton servBtn;
    private javax.swing.JPanel servPnl;
    // End of variables declaration//GEN-END:variables
}
