/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import com.dataStructures.MyContainer;
import com.dataStructures.MyVisitor;
import static com.main.MainMenuTest.contentPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author NUHU
 */
public class RemoveDefected extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    Options main;
    public RemoveDefected(Options main) {
        initComponents();
        this.main=main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        uDemo16 = new javax.swing.JLabel();
        validate = new javax.swing.JButton();
        productID = new javax.swing.JTextField();
        uDemo14 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        uDemo15 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        uDemo18 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        productID1 = new javax.swing.JTextField();
        uDemo17 = new javax.swing.JLabel();
        reason = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(360, 347));
        setPreferredSize(new java.awt.Dimension(715, 393));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REMOVE DEFECTED DRUG FROM INVENTORY");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 710, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 12, 92)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("Drug ID");
        jPanel2.add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 40));

        validate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validate.setText("Validate ID");
        validate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });
        jPanel2.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, 35));

        productID.setBackground(new java.awt.Color(204, 204, 255));
        productID.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        productID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDActionPerformed(evt);
            }
        });
        jPanel2.add(productID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 300, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 460, 100));

        uDemo14.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo14.setForeground(new java.awt.Color(0, 0, 102));
        uDemo14.setText("Drug Name");
        add(uDemo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 130, 30));

        productName.setEditable(false);
        productName.setBackground(new java.awt.Color(204, 204, 255));
        productName.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 360, -1));

        close.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        close.setText("Close");
        close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 90, 35));

        uDemo15.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo15.setForeground(new java.awt.Color(0, 0, 102));
        uDemo15.setText("Qty to remove");
        add(uDemo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 150, 30));

        qty.setBackground(new java.awt.Color(204, 204, 255));
        qty.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        qty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 360, -1));

        uDemo18.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo18.setForeground(new java.awt.Color(0, 0, 102));
        uDemo18.setText("Drug ID");
        add(uDemo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 30));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update Inventory");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 190, 35));

        productID1.setEditable(false);
        productID1.setBackground(new java.awt.Color(204, 204, 255));
        productID1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        productID1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        productID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productID1ActionPerformed(evt);
            }
        });
        add(productID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 360, -1));

        uDemo17.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo17.setForeground(new java.awt.Color(0, 0, 102));
        uDemo17.setText("Reason");
        add(uDemo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 150, 30));

        reason.setBackground(new java.awt.Color(204, 204, 255));
        reason.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        reason.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 360, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        MainMenuTest.contentPanel.removeAll();
        MainMenuTest.contentPanel.setVisible(false);
        MainMenuTest.contentPanel.setVisible(true);
        
        main.refresh();
    }//GEN-LAST:event_closeActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditProduct editForm = new EditProduct(main);
                contentPanel.removeAll();
                contentPanel.add(editForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));//, 620, 477) );
                try {
                    contentPanel.setVisible(false);
                    contentPanel.setVisible(true);
                } catch (Exception e) {
                    //JOptionPane.showMessageDialog(null, e.getMessage());
                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                }
            }
        };
        runner.start();
    }
    
    public String ucfirst(String s){
        try{
            String first, second;
            first=s.substring(0,1);
            second=s.substring(1);
            return first.toUpperCase()+second.toLowerCase();
        }catch(Exception ex){
            return "";
        }
    }
        
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String productID1=this.productID1.getText().trim();
        String productName=this.productName.getText().trim();
        String qty= this.qty.getText().trim();
        String reason=this.reason.getText().trim();
        
        productID1=ucfirst(productID1);
        reason= reason.toUpperCase();
        MyContainer c= new MyContainer();
        
        String patProductID = "^[a-zA-Z0-9]{6}$";
        String patProductName = "^[a-zA-Z0-9].{3,30}$";
        String patQty = "^(0)|(\\+)?[1-9][0-9]{0,}$";
 
        if(!Pattern.matches(patProductID, productID1)){
            c.insert("Invalid Drug ID");
        }
        if(!Pattern.matches(patProductName, productName)){
            c.insert("Invalid Drug Name");
        }
        if(!Pattern.matches(patQty, qty)){
            c.insert("Invalid Drug Quantity");
        }
        
        if(!Pattern.matches(patProductName, reason)){
            c.insert("Kindly enter a reason for Drug defect");
        }
        
        if(this.productID1.getText().equals("") || this.reason.getText().equals(" ") || this.productName.getText().equals("") || this.qty.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empty Fields","Error!",JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else if(c.getCount()!=0){
            MyVisitor v= new MyVisitor();
            c.accept(v);
            
            JOptionPane.showMessageDialog(null,v.getErrors(), "Error!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                PreparedStatement st;
                String sql="select * from inventory where productID=?";
                st=DBConnect.con.prepareStatement(sql);
                st.setString(1, productID1);
                DBConnect.rs=st.executeQuery();
                int oldQty=0;
                if(DBConnect.rs.next()){
                    oldQty=DBConnect.rs.getInt("Qty");
                }
                java.util.Date today= new java.util.Date();
                SimpleDateFormat ft= new SimpleDateFormat("yyyy-MM-dd");
                String date= ft.format(today);
                //Update the info]
                if(oldQty>=Integer.parseInt(qty)){
                    DBConnect.con.setAutoCommit(false);

                    sql="update inventory set qty=? where productID=?";
                    st= DBConnect.con.prepareStatement(sql);

                    st.setInt(1, (oldQty - Integer.parseInt(qty)));
                    st.setString(2, productID1);

                    st.executeUpdate();

                    sql="insert into inventorytrack values (?,?,?,?,?,?,?)";
                    st= DBConnect.con.prepareStatement(sql);
                    st.setString(1, productID1);
                    st.setInt(2, (oldQty-Integer.parseInt(qty)));
                    st.setInt(3, 0);
                    st.setInt(4, Integer.parseInt(qty));
                    st.setString(5, "OUT");
                    st.setString(6, reason);
                    st.setString(7, date);
                    st.executeUpdate();

                    DBConnect.con.commit();
                    JOptionPane.showMessageDialog(null, "Information Updated","Success!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-199-ok-circle.png")));
                    //Refresh page
                    refresh();
                }else{
                    JOptionPane.showMessageDialog(null, "Quantity of "+productName+" in stock is not sufficient","Issue!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                }
            }catch(SQLException ex){
                try{
                    JOptionPane.showMessageDialog(null, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    System.out.println(ex.getMessage());
                    DBConnect.con.rollback();
                }catch(SQLException sqlEx){
                    
                }
                JOptionPane.showMessageDialog(null, "Issue excecuting query","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
            }finally{
                c.purge();
                DBConnect.rs=null;
                try{
                    DBConnect.con.setAutoCommit(true);
                }catch(SQLException sqlEx){
                    
                }
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        String productID=this.productID.getText().trim();
        
        String patProductID = "^[a-zA-Z0-9]{6}$";
        if(!Pattern.matches(patProductID, productID)){
            JOptionPane.showMessageDialog(null, "Invalid Drug ID","Issue!",JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                PreparedStatement st;
                String sql="select product.productID, product.productName, qty from product, inventory where product.productID=? and product.productID=inventory.productID";
                st=DBConnect.con.prepareStatement(sql);
                st.setString(1, productID);
                DBConnect.rs=st.executeQuery();
                if(DBConnect.rs.next()){
                    productID1.setText(DBConnect.rs.getString(1));
                    productName.setText(DBConnect.rs.getString(2));
                }else{
                    JOptionPane.showMessageDialog(null, "Drug ID does not exist","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                    productID1.setText("");
                    productName.setText("");
                    qty.setText("");
                    reason.setText("");
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(null, "Issues excecuting query","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                //JOptionPane.showMessageDialog(null, sqlEx.getMessage());
                productID1.setText("");
                productName.setText("");
                qty.setText("");
                reason.setText("");
            }
        }        
    }//GEN-LAST:event_validateActionPerformed

    private void productIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDActionPerformed

    private void productID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productID1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productID1;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField reason;
    private javax.swing.JLabel uDemo14;
    private javax.swing.JLabel uDemo15;
    private javax.swing.JLabel uDemo16;
    private javax.swing.JLabel uDemo17;
    private javax.swing.JLabel uDemo18;
    private javax.swing.JButton update;
    private javax.swing.JButton validate;
    // End of variables declaration//GEN-END:variables
}
