/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;

import com.dataStructures.MyContainer;
import com.dataStructures.MyVisitor;
import static com.main.MainMenuTest.contentPanel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author NUHU
 */
public class Service extends javax.swing.JPanel {

    /**
     * Creates new form AddUser
     */
    ProcessSales sales;
    public Service(ProcessSales sales) {
        this.sales=sales;
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uDemo16 = new javax.swing.JLabel();
        uDemo14 = new javax.swing.JLabel();
        serviceID = new javax.swing.JTextField();
        addTrans = new javax.swing.JButton();
        charge = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(360, 347));
        setPreferredSize(new java.awt.Dimension(278, 176));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SERVICE INFORMATION");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("Service ID");
        add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        uDemo14.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo14.setForeground(new java.awt.Color(0, 0, 102));
        uDemo14.setText("Charge");
        add(uDemo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));

        serviceID.setBackground(new java.awt.Color(204, 204, 255));
        serviceID.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        serviceID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(serviceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, -1));

        addTrans.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addTrans.setText("Add Transaction");
        addTrans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        addTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransActionPerformed(evt);
            }
        });
        add(addTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 35));

        charge.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        charge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    ", "HOME", "REGULAR" }));
        add(charge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, 30));
    }// </editor-fold>//GEN-END:initComponents
    
    public String ucfirst(String s){
        try{
            String first, second;
            first=s.substring(0,1);
            second=s.substring(1);
            return first.toUpperCase()+second.toLowerCase();
        }catch(Exception ex){
            return "";
        }
    }
    
    private void addTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransActionPerformed
        String serviceID=this.serviceID.getText().trim();
        String charge=""+this.charge.getSelectedItem();
        
        MyContainer c= new MyContainer();
        
        String patServiceID = "^[a-zA-Z0-9]{6}$";
        
        if(!Pattern.matches(patServiceID, serviceID)){
            c.insert("Invalid Service ID");
        }
        if( this.serviceID.equals("")|| this.charge.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Empty Fields","Error!",JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
        }else if(c.getCount()!=0){
            
            MyVisitor v= new MyVisitor();
            c.accept(v);
            
            JOptionPane.showMessageDialog(null,v.getErrors(), "Error!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));  
        }else{
            try{
                String sql="select * from service where serviceID='"+serviceID+"'";
                DBConnect.rs= DBConnect.st.executeQuery(sql);
                if(DBConnect.rs.next()){
                    java.util.Date today= new java.util.Date();
                    SimpleDateFormat ft= new SimpleDateFormat("yyyy-MM-dd");
                    String date= ft.format(today);
                    PreparedStatement st;
                    sql="insert into tempsalestbl(ID, name, quantity, amount, date, type) values (?, ?, ?, ?, ?, ?)";
                    st=DBConnect.con.prepareStatement(sql);
                    st.setString(1, serviceID);
                    st.setString(2, DBConnect.rs.getString("serviceName"));
                    st.setString(3, "1");
                    if(charge.equals("REGULAR")){
                        st.setDouble(4, DBConnect.rs.getDouble("chargeRegular"));
                    }else if(charge.equals("HOME")){
                        st.setDouble(4, DBConnect.rs.getDouble("chargeHome"));
                    }
                    st.setString(5, date);
                    st.setString(6, "SERVICE");
                    st.executeUpdate();

                    sales.createTable();

                    this.serviceID.setText("");
                    this.charge.setSelectedIndex(0);
                }else{
                    JOptionPane.showMessageDialog(null, "Service ID does not exist","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
                }
            }catch(SQLException ex){
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(null, "Issue excecuting query","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/png/glyphicons-197-exclamation-sign.png")));
            }
        }
    }//GEN-LAST:event_addTransActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrans;
    private javax.swing.JComboBox charge;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField serviceID;
    private javax.swing.JLabel uDemo14;
    private javax.swing.JLabel uDemo16;
    // End of variables declaration//GEN-END:variables
}
