/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.main;


import com.dataStructures.MyTable;
import com.dataStructures.ResultSetTableModel;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author NUHU
 */
public class ViewService extends javax.swing.JPanel {

    /**
     * Creates new form CourseReg
     */
    Options main;
    public ViewService(Options main) {
        this.main=main;
        DBConnect.connect();
        initComponents();
        createTable();
    }
    private JTable table;
    private JTable table1;
    private TableColumn column = null;
    private JScrollPane scrollPane;
    private ResultSetTableModel tableModel;
    
    private void createTable(){
        String sql="select serviceID, serviceName, chargeRegular, chargeHome from service";
        JTable table;
        TableColumn column = null;
        JScrollPane scrollPane;
        
        String meta[]={"Service ID", "Service Name", "Charge(Regular)", "Charge(Home Service)"};
        
        table= MyTable.createTable(sql, meta);
 
        table.setPreferredScrollableViewportSize(new Dimension(650, 210));
        
        scrollPane = new JScrollPane(table);
        
        for (int i = 0; i < 4; i++) {
                column = table.getColumnModel().getColumn(i);
                if (i == 0) //MemberID
                        column.setPreferredWidth(50);
                if (i == 1) //ID
                        column.setPreferredWidth(70);
                if (i == 2) //MemberID
                        column.setPreferredWidth(120);
                if (i == 3) //ID
                        column.setPreferredWidth(120);
        }
     
        contentPanel.removeAll();
        
        scrollPane.setViewportView(table);
        
        contentPanel.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 210));
        contentPanel.setVisible(false);
        contentPanel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        compute2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(743, 314));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 650, 210));

        compute2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        compute2.setText("Close");
        compute2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        compute2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compute2ActionPerformed(evt);
            }
        });
        add(compute2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 180, 40));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VIEW ALL SERVICE");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 720, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void compute2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compute2ActionPerformed
        MainMenuTest.contentPanel.removeAll();
        MainMenuTest.contentPanel.setVisible(false);
        MainMenuTest.contentPanel.setVisible(true);
        
        main.refresh();
    }//GEN-LAST:event_compute2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compute2;
    public static javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
